### ISSUE TITLE
Registering handlebars partials

### ISSUE THREAD

**Issue by kvzivn** [segmentio/metalsmith#152]
Wasn't sure where to post this issue.

I have tried registering partials with metalsmith-register-partials, metalsmith-partials and by adding the register to my index.js:

`Handlebars.registerPartial('header', fs.readFileSync(__dirname + '/templates/partials/header.hbt').toString());`

Getting same error with all of them:

```
  Metalsmith · The partial header could not be found

Error: The partial header could not be found
    at Object.invokePartial (/Users/keiv/dev/github/blog/node_modules/handlebars/dist/cjs/handlebars/runtime.js:216:11)
    at Object.invokePartialWrapper [as invokePartial] (/Users/keiv/dev/github/blog/node_modules/handlebars/dist/cjs/handlebars/runtime.js:61:39)
    at Object.eval (eval at createFunctionContext (/Users/keiv/dev/github/blog/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:221:23), <anonymous>:5:26)
    at ret (/Users/keiv/dev/github/blog/node_modules/handlebars/dist/cjs/handlebars/runtime.js:159:30)
    at ret (/Users/keiv/dev/github/blog/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:488:21)
    at Function.exports.handlebars.render (/Users/keiv/dev/github/blog/node_modules/metalsmith-layouts/node_modules/consolidate/lib/consolidate.js:497:14)
    at /Users/keiv/dev/github/blog/node_modules/metalsmith-layouts/node_modules/consolidate/lib/consolidate.js:146:25
    at /Users/keiv/dev/github/blog/node_modules/metalsmith-layouts/node_modules/consolidate/lib/consolidate.js:99:5
    at fs.js:334:14
    at FSReqWrap.oncomplete (fs.js:95:15)
```

Might have to do something with metalsmith-templates being deprecated and split into two other plugins that don't support this? (metalsmith-layouts & metalsmith-in-place)

**Comment by kvzivn** [comment]
Never mind. Turned out I was loading the partials in my metalsmith.json *after* using the metalsmith-layout plugin. Sigh.
