### ISSUE TITLE
"ENOTEMPTY, directory not empty" error

### ISSUE THREAD

**Issue by misterdai** [segmentio/metalsmith#69]
When executing Metalsmith on my Windows machine, I sometimes receive the following error:

```
Error: ENOTEMPTY, directory not empty 'C:\Projects\metalsmith\build\2013\05\21'
  at Object.fs.rmdirSync (fs.js:612:18)
  at rmkidsSync (C:\Projects\metalsmith\node_modules\metalsmith\node_modules\rim
raf\rimraf.js:247:11)
  at rmdirSync (C:\Projects\metalsmith\node_modules\metalsmith\node_modules\rimr
af\rimraf.js:237:7)
  at fixWinEPERMSync (C:\Projects\metalsmith\node_modules\metalsmith\node_module
s\rimraf\rimraf.js:150:5)
  at rimrafSync (C:\Projects\metalsmith\node_modules\metalsmith\node_modules\rim
raf\rimraf.js:216:26)
  at C:\Projects\metalsmith\node_modules\metalsmith\node_modules\rimraf\rimraf.j
s:245:5
  at Array.forEach (native)
  at rmkidsSync (C:\Projects\metalsmith\node_modules\metalsmith\node_modules\rim
raf\rimraf.js:244:26)
  at rmdirSync (C:\Projects\metalsmith\node_modules\metalsmith\node_modules\rimr
af\rimraf.js:237:7)
  at fixWinEPERMSync (C:\Projects\metalsmith\node_modules\metalsmith\node_module
s\rimraf\rimraf.js:150:5)
  at rimrafSync (C:\Projects\metalsmith\node_modules\metalsmith\node_modules\rim
raf\rimraf.js:216:26)
  at C:\Projects\metalsmith\node_modules\metalsmith\node_modules\rimraf\rimraf.j
s:245:5
  at Array.forEach (native)
  at rmkidsSync (C:\Projects\metalsmith\node_modules\metalsmith\node_modules\rim
raf\rimraf.js:244:26)
  at rmdirSync (C:\Projects\metalsmith\node_modules\metalsmith\node_modules\rimr
af\rimraf.js:237:7)
  at fixWinEPERMSync (C:\Projects\metalsmith\node_modules\metalsmith\node_module
s\rimraf\rimraf.js:150:5)
  at rimrafSync (C:\Projects\metalsmith\node_modules\metalsmith\node_modules\rim
raf\rimraf.js:216:26)
  at C:\Projects\metalsmith\node_modules\metalsmith\node_modules\rimraf\rimraf.j
s:245:5
  at Array.forEach (native)
  at rmkidsSync (C:\Projects\metalsmith\node_modules\metalsmith\node_modules\rim
raf\rimraf.js:244:26)
  at rmdirSync (C:\Projects\metalsmith\node_modules\metalsmith\node_modules\rimr
af\rimraf.js:237:7)
  at fixWinEPERMSync (C:\Projects\metalsmith\node_modules\metalsmith\node_module
s\rimraf\rimraf.js:150:5)
  at rimrafSync (C:\Projects\metalsmith\node_modules\metalsmith\node_modules\rim
raf\rimraf.js:216:26)
  at Metalsmith.write (C:\Projects\metalsmith\node_modules\metalsmith\lib\index.
js:214:14)
  at C:\Projects\metalsmith\node_modules\metalsmith\lib\index.js:141:12
  at next (C:\Projects\metalsmith\node_modules\metalsmith\node_modules\ware\lib\
index.js:60:42)
  at C:\Projects\metalsmith\node_modules\metalsmith-assets\index.js:50:9
  at done (C:\Projects\metalsmith\node_modules\metalsmith-assets\node_modules\as
ync\lib\async.js:128:19)
  at C:\Projects\metalsmith\node_modules\metalsmith-assets\node_modules\async\li
b\async.js:25:16
  at C:\Projects\metalsmith\node_modules\metalsmith-assets\index.js:66:11
  at fs.js:266:14
  at Object.oncomplete (fs.js:107:15)
```

If I run a second time or manually delete the `build` directory before execution, it works 100% of the time.

I believe it might have something to do with the way files are deleted in Windows, as I think I read that Node only marks files for deletion and doesn't actually delete them itself.  This may be causing a long enough delay, before Windows actually performs the delete, that the directory removal step is being performed while the files still exist.

**Comment by ianstormtaylor** [comment]
Closing with @serebrov's explanation, but feel free to reopen.

**Comment by ubenzer** [comment]
Please note that, you can see the same error if you have a Finder window open in Metalsmith target directory while running Metalsmith.

Metalsmtih tries to remove directories and files but OSX creates .DS_Store file as soon as Metalsmith deletes it causing directory beign non-empty.
